### PR TITLE
Re-add OS X support, fix underwater audio filter

### PR DESCRIPTION
**Pull request by Jarvik7**
No changes to source were needed, just to makefile.
The build process is now also different.
Frameworks are no longer needed, but instead you will need to get some packages
from Homebrew to compile.

Get homebrew, then install the following packages before compiling.

openal-soft
libogg
libvorbis
sdl2

Note that this has only been tested on OS X 10.10 (Yosemite) on x86-64.

### CODE REVIEW

**Comment by Yamagi** [comment]
This looks very, very good. Thank you :)

But to be clear: I won't be able to build binaries, since I don't have a Mac. This hackintosh stuff is much too unstable and too illegal.

**Comment by Jarvik7** [comment]
Thanks for the merge.

When I get the chance I'm going to modify the Makefile to build the .app instead of needing to include it in the .zip. Ideally the only extra thing that will need to be included is the icon.

The readme/docs need a revert & compilation instructions too.

**Comment by Diskutant** [comment]
I have an old MacBook Intel CoreDuo (32bit) here, it runs OS X 10.4.4 up to 10.6.8
I have it at 10.6.8 installed homebrew tried to get openal-soft installed, but it had some errors with one of it's dependencies. I tried macports then, they still have some legacy downloads, with that I was able to install all the dependencies (took almost a full day) but in the end I wasn't able to compile yquake2.

I tried the whole thing with my other MacBook which runs OS X 10.10.2. I installed the dependencies with homebrew (took only a minute too install everything) and yquake2 compiled just fine.
But it crashes when I start it. So I need to investigate further, but I am willing to do automatic builds it's just that I am no pro at finding the errors without an IDE and stuff.

Also I think we (you) should move the supported OS X version up to 10.7 and up. 10.5 is really damn old and no one really uses it anymore, it's not supported by Apple anymore either, so it gets no security updates.

**Comment by Jarvik7** [comment]
I'm guessing the problem on your old machine is 32-bit support. the makefile for my commit is set to arch=x86_64. You can search & replace this with "i386" and try again if you want. I'll try to make a 32bit binary and see if that is the only problem.

As for your 10.10 machine please check your console for error messages or the crash log. Afraid I can't do anything without that.

**Comment by Jarvik7** [comment]
Re:32bit
I recompiled in 32bit with all universal libs (brew install SDL2 --universal, etc) and it's working fine for me now. I will make a new pull request later today for that, but I'll still need your crash logs etc.
Also try running ./quake2 from inside the app in your terminal to get verbose output.

**Comment by Diskutant** [comment]
On the 32bit Mac with OS X 10.6.8 I have trouble with OpenAL as it seems:

Build configuration
============================
WITH_CDA = yes
WITH_OPENAL = yes
WITH_SDL2 = no
WITH_X11GAMMA = no
WITH_ZIP = yes
WITH_SYSTEMWIDE = no
WITH_SYSTEMDIR = 
============================

===> Building quake2
make release/quake2
===> CC src/backends/generic/qal.c
src/backends/generic/qal.c:35:19: error: AL/al.h: No such file or directory
src/backends/generic/qal.c:36:20: error: AL/alc.h: No such file or directory
src/backends/generic/qal.c:37:22: error: AL/alext.h: No such file or directory
In file included from src/backends/generic/qal.c:41:
src/backends/generic/header/qal.h:35:21: error: AL/efx.h: No such file or directory
In file included from src/backends/generic/qal.c:41:

**Comment by Jarvik7** [comment]
It looks like OpenAL isn't installed.
What does 'brew info openal-soft' say?

You can try installing it with brew install openal-soft --universal

**Comment by Diskutant** [comment]
brew can't install OpenAL on a OS X that old. That's why I had to use macports as I stated last week 

Quote: "I have it at 10.6.8 installed homebrew tried to get openal-soft installed, but it had some errors with one of it's dependencies. I tried macports then, they still have some legacy downloads, with that I was able to install all the dependencies (took almost a full day) but in the end I wasn't able to compile yquake2."

'port installed' lists "openal-soft @1.15.1_1 (active)" among many others

**Comment by Diskutant** [comment]
I just did a new build on my 10.10 machine, that one works now, I think I just had some errors in moving the files to the right places. 

I think I missed your question last time,  "uname -m | sed -e s/i.86/i386/" on the 32bit Mac shows "i386"

What do I need to do to do a 32bit or univeral build on the 10.10 Mac?

**Comment by Jarvik7** [comment]
1) Make sure all the dependencies I listed are installed in homebrew using the --universal switch.
2) Edit line 76 in the makefile
OSX_ARCH:=-arch $(shell uname -m | sed -e s/i.86/i386/)
change to
OSX_ARCH:=-arch i386

This will make a 32bit binary. You can try changing it to the following to make a universal binary, but I haven't tried if it works:
OSX_ARCH:=-arch i386 -arch x86_64

If the universal setting works on both your macs let me know and I'll make it the default.

**Comment by Diskutant** [comment]
can't get openal-soft installed with the universal switch:

brew remove openal-soft libogg libvorbis sdl2
Uninstalling /usr/local/Cellar/openal-soft/1.16.0...
Uninstalling /usr/local/Cellar/libogg/1.3.2...
Uninstalling /usr/local/Cellar/libvorbis/1.3.5...
Uninstalling /usr/local/Cellar/sdl2/2.0.3...

brew install openal-soft --universal
==> Downloading http://kcat.strangesoft.net/openal-releases/openal-soft-1.16.0.tar.bz2
Already downloaded: /Library/Caches/Homebrew/openal-soft-1.16.0.tar.bz2
==> cmake . -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/openal-soft/1.16.0 -DCMAKE_BUILD_TYPE=None -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFIL
==> make install
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [alsoft-config] Error 1
make[1]: *** [utils/alsoft-config/CMakeFiles/alsoft-config.dir/all] Error 2
make: *** [all] Error 2

**Comment by Jarvik7** [comment]
Weird, it built with no problems for me.

Try:
brew uninstall openal-soft
brew cleanup
brew cleanup -s
brew doctor (see if anything is reported)
brew install openal-soft --universal

**Comment by Diskutant** [comment]
Ok, got it to build. It was a missing path in $PATH I thought when I switch user using su user I would get that users path variables, but I got those from the first user.

But I can't execute it on the 32bit mac. Then I realised I build against sdl2 dynamically. But I can't get sdl2 on the old mac installed. So I tried to build using sdl, but that gave me another error:

make
Build configuration
============================
WITH_CDA = yes
WITH_OPENAL = yes
WITH_SDL2 = no
WITH_X11GAMMA = no
WITH_ZIP = yes
WITH_SYSTEMWIDE = no
WITH_SYSTEMDIR = 
============================

===> Building quake2
/Applications/Xcode.app/Contents/Developer/usr/bin/make release/quake2
===> CC src/backends/generic/qal.c
===> CC src/backends/generic/vid.c
===> CC src/backends/generic/qgl.c
===> CC src/backends/sdl/cd.c
===> CC src/backends/sdl/input.c
src/backends/sdl/input.c:419:9: error: use of undeclared identifier 'SDL_WINDOWEVENT_FOCUS_LOST'
                        case SDL_WINDOWEVENT_FOCUS_LOST:
                             ^
1 error generated.
make[1]: *** [build/client/src/backends/sdl/input.o] Error 1
make: *** [client] Error 2

**Comment by Jarvik7** [comment]
I haven't looked at the SDL1 build path at all yet.

Could you not install SDL2 on your 32bit machine using homebrew? You only mentioned that OpenAL wouldn't work.

You could just copy the universal dylibs from your 64bit machine into the /usr/local/lib folder until I redo the makefile to copy them into the .app

**Comment by Diskutant** [comment]
brew install sdl2
==> Downloading http://libsdl.org/release/SDL2-2.0.3.tar.gz
Already downloaded: /Library/Caches/Homebrew/sdl2-2.0.3.tar.gz
==> ./configure --prefix=/usr/local/Cellar/sdl2/2.0.3 --without-x
==> make install
/private/tmp/sdl220150403-86673-1xt93aa/SDL2-2.0.3/src/video/cocoa/SDL_cocoaopengl.m: In function 'Cocoa_GL_GetDrawableSize':
/private/tmp/sdl220150403-86673-1xt93aa/SDL2-2.0.3/src/video/cocoa/SDL_cocoaopengl.m:351: error: incompatible types in assignment
libtool: compile:  gcc-4.2 -g -O3 -DUSING_GENERATED_CONFIG_H -Iinclude -I/private/tmp/sdl220150403-86673-1xt93aa/SDL2-2.0.3/include -mmmx -m3dnow -msse -msse2 -DTARGET_API_MAC_CARBON -DTARGET_API_MAC_OSX -fvisibility=hidden -D_THREAD_SAFE -fpascal-strings -Wall -MMD -MT build/SDL_cocoamousetap.lo -c /private/tmp/sdl220150403-86673-1xt93aa/SDL2-2.0.3/src/video/cocoa/SDL_cocoamousetap.m -o build/SDL_cocoamousetap.o >/dev/null 2>&1
make: *** [build/SDL_cocoaopengl.lo] Error 1
make: *** Waiting for unfinished jobs....
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
SDL2 failed to build on 10.6 (https://github.com/Homebrew/homebrew/issues/37837)


But I just remembered that I just downloaded the official SDL2 binary and copied that to /Library/Frameworks/SDL2.framework


The errors I get from Yquake2 crashing are not helpful either:

Process:         bash [86602]
Path:            /bin/bash
Identifier:      bash
Version:         ??? (???)
Code Type:       X86 (Native)
Parent Process:  bash [86592]

Date/Time:       2015-04-03 14:37:34.649 +0200
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00000000fffffffc
Crashed Thread:  Unknown

Backtrace not available

Unknown thread crashed with X86 Thread State (32-bit):
  eax: 0x00000055  ebx: 0x00000000  ecx: 0x00000000  edx: 0x00000000
  edi: 0x00000000  esi: 0x00000000  ebp: 0x00000000  esp: 0x00000000
   ss: 0x0000001f  efl: 0x00010203  eip: 0x8fe01030   cs: 0x00000017
   ds: 0x0000001f   es: 0x0000001f   fs: 0x00000000   gs: 0x00000000
  cr2: 0xfffffffc

Binary images description not available

**Comment by DanielGibson** [comment]
You may wanna use the "Development Libraries" from 
http://libsdl.org/download-2.0.php

**Comment by Diskutant** [comment]
That's the one I downloaded on the old Mac.

**Comment by Jarvik7** [comment]
I've had nothing but nightmares with fink & macports, so I can't really help in that area re conflicts etc.
What version of Xcode is on your 32bit mac? It sounds like SDL2 simply doesn't compile in that ver.

Also, we are using dylibs, not frameworks, so you'll need the actual .dylib file. Copying them from your 64bit machine is probably easiest like I said.

To get verbose crash messages etc, go into the .app file in terminal and run the actual binary (contents/resources/quake2)

**Comment by DanielGibson** [comment]
I think on the SDL mailing list it was mentioned that SDL2 doesn't 
compile anymore on old OSX versions.
It must be compiled on a newer one (don't remember what the minimum 
version was), with backwards compatibility settings.
That way a binary that will support down to 10.5 can be created (like 
the one downloaded there).
So don't try to build SDL2 yourself, try to make yquake2 use the one 
downloaded from libsdl.org

**Comment by Diskutant** [comment]
ok I copied the files 
libSDL2_test.a
libSDL2-2.0.0.dylib
libSDL2.a
libSDL2.dylib
libSDL2main.a
from my new mac to the old mac into /opt/local/lib

is that right?

Didn't help at all.
Starting quake2 using the terminal just states "Illegal instruction"

**Comment by Jarvik7** [comment]
/usr/local/lib is what Homebrew uses and what the binary will look for.
Here is a list of the needed dylibs and their path:
otool -L quake2
quake2:
	/usr/local/lib/libvorbis.0.dylib (compatibility version 5.0.0, current version 5.8.0)
	/usr/local/lib/libvorbisfile.3.dylib (compatibility version 7.0.0, current version 7.7.0)
	/usr/local/lib/libogg.0.dylib (compatibility version 9.0.0, current version 9.2.0)
	/usr/local/lib/libSDL2-2.0.0.dylib (compatibility version 3.0.0, current version 3.1.0)

Hopefully libogg and libvorbis could install through homebrew as they look like a mess to copy manually due to recursive dependencies.

**Comment by Diskutant** [comment]
oh well, my output is different:

otool -L quake2
quake2:
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	/usr/local/lib/libvorbis.0.dylib (compatibility version 5.0.0, current version 5.8.0)
	/usr/local/lib/libvorbisfile.3.dylib (compatibility version 7.0.0, current version 7.7.0)
	/usr/local/lib/libogg.0.dylib (compatibility version 9.0.0, current version 9.2.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.5)
	/usr/local/lib/libSDL2-2.0.0.dylib (compatibility version 3.0.0, current version 3.1.0)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 21.0.0)

**Comment by Jarvik7** [comment]
It's the same, I just deleted all the lines for system libs before posting.

**Comment by Diskutant** [comment]
oh I see.

the four files are in place, but nothing changes about yquake. Starting the ./quake2 gives Illegal Instruction, and starting Quake2.app quits when pressing Start and gives still the same bash crashlog as before

**Comment by Jarvik7** [comment]
It sounds like an issue with the compilation environment on your 32bit machine.
Maybe tomorrow I can throw together a zip of the 32bit application & dylib binaries I compiled here.

**Comment by Diskutant** [comment]
the 32bit version is compiled on my new mac using OS X 10.10.2

trying to compile on the old mac still gives the missing openal errors:
src/backends/generic/qal.c:35:19: error: AL/al.h: No such file or directory
etc.
